name: remote_assets_gen
description: A code generator for your remote assets stored in AWS S3. It's a modification of the great flutter_gen package to support fetching assets from a remote source instead of local project assets.
version: 0.0.1
homepage: https://github.com/abdelazizrashed/remote-assets-gen
repository: https://github.com/abdelazizrashed/remote-assets-gen
issue_tracker: https://github.com/abdelazizrashed/remote-assets-gen/issues

environment:
  sdk: ^3.5.3

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.0
  mime: '>=1.0.0 <3.0.0'
  dartx: ^1.0.0
  collection: ^1.15.0
  dart_style: ^3.0.0
  archive: '>=3.4.0 <5.0.0'
  pub_semver: ^2.0.0
  aws_client: ^0.7.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
