name: remote_assets_gen
description: A code generator for your remote assets stored in AWS S3. It's a modification of the great flutter_gen package to support fetching assets from a remote source instead of local project assets.
version: 0.0.1
homepage: https://github.com/abdelazizrashed/remote-assets-gen
repository: https://github.com/abdelazizrashed/remote-assets-gen
issue_tracker: https://github.com/abdelazizrashed/remote-assets-gen/issues

environment:
  sdk: ^3.5.3

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  aws_client: ^0.7.1
  dart_style: ^3.1.2
  logging: ^1.3.0
  path: ^1.9.1
  archive: ^4.0.7
  dartx: ^1.2.0
  mime: ^2.0.0
  pub_semver: ^2.2.0
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
